// Nigerian states with their respective capital cities
export const nigerianStates = [
  { label: "Abia", value: "abia", capital: "Umuahia" },
  { label: "Adamawa", value: "adamawa", capital: "Yola" },
  { label: "Akwa Ibom", value: "akwa_ibom", capital: "Uyo" },
  { label: "Anambra", value: "anambra", capital: "Awka" },
  { label: "Bauchi", value: "bauchi", capital: "Bauchi" },
  { label: "Bayelsa", value: "bayelsa", capital: "Yenagoa" },
  { label: "Benue", value: "benue", capital: "Makurdi" },
  { label: "Borno", value: "borno", capital: "Maiduguri" },
  { label: "Cross River", value: "cross_river", capital: "Calabar" },
  { label: "Delta", value: "delta", capital: "Asaba" },
  { label: "Ebonyi", value: "ebonyi", capital: "Abakaliki" },
  { label: "Edo", value: "edo", capital: "Benin City" },
  { label: "Ekiti", value: "ekiti", capital: "Ado-Ekiti" },
  { label: "Enugu", value: "enugu", capital: "Enugu" },
  { label: "Federal Capital Territory", value: "fct", capital: "Abuja" },
  { label: "Gombe", value: "gombe", capital: "Gombe" },
  { label: "Imo", value: "imo", capital: "Owerri" },
  { label: "Jigawa", value: "jigawa", capital: "Dutse" },
  { label: "Kaduna", value: "kaduna", capital: "Kaduna" },
  { label: "Kano", value: "kano", capital: "Kano" },
  { label: "Katsina", value: "katsina", capital: "Katsina" },
  { label: "Kebbi", value: "kebbi", capital: "Birnin Kebbi" },
  { label: "Kogi", value: "kogi", capital: "Lokoja" },
  { label: "Kwara", value: "kwara", capital: "Ilorin" },
  { label: "Lagos", value: "lagos", capital: "Ikeja" },
  { label: "Nasarawa", value: "nasarawa", capital: "Lafia" },
  { label: "Niger", value: "niger", capital: "Minna" },
  { label: "Ogun", value: "ogun", capital: "Abeokuta" },
  { label: "Ondo", value: "ondo", capital: "Akure" },
  { label: "Osun", value: "osun", capital: "Osogbo" },
  { label: "Oyo", value: "oyo", capital: "Ibadan" },
  { label: "Plateau", value: "plateau", capital: "Jos" },
  { label: "Rivers", value: "rivers", capital: "Port Harcourt" },
  { label: "Sokoto", value: "sokoto", capital: "Sokoto" },
  { label: "Taraba", value: "taraba", capital: "Jalingo" },
  { label: "Yobe", value: "yobe", capital: "Damaturu" },
  { label: "Zamfara", value: "zamfara", capital: "Gusau" },
];

// Educational levels commonly used in Nigerian educational system
export const educationalLevels = [
  { label: "100 Level", value: "100" },
  { label: "200 Level", value: "200" },
  { label: "300 Level", value: "300" },
  { label: "400 Level", value: "400" },
  { label: "500 Level", value: "500" },
  { label: "600 Level", value: "600" },
  { label: "Postgraduate", value: "postgraduate" },
];

// Common gender options
export const genderOptions = [
  { label: "Male", value: "male" },
  { label: "Female", value: "female" },
];

// Common Nigerian university departments
export const commonDepartments = [
  { label: "Accounting", value: "accounting" },
  { label: "Agricultural Science", value: "agricultural_science" },
  { label: "Architecture", value: "architecture" },
  { label: "Banking and Finance", value: "banking_and_finance" },
  { label: "Biochemistry", value: "biochemistry" },
  { label: "Business Administration", value: "business_administration" },
  { label: "Chemical Engineering", value: "chemical_engineering" },
  { label: "Civil Engineering", value: "civil_engineering" },
  { label: "Computer Engineering", value: "computer_engineering" },
  { label: "Computer Science", value: "computer_science" },
  { label: "Economics", value: "economics" },
  {
    label: "Electrical/Electronic Engineering",
    value: "electrical_engineering",
  },
  { label: "English Language", value: "english_language" },
  { label: "Geology", value: "geology" },
  { label: "History", value: "history" },
  { label: "Law", value: "law" },
  { label: "Mass Communication", value: "mass_communication" },
  { label: "Mathematics", value: "mathematics" },
  { label: "Mechanical Engineering", value: "mechanical_engineering" },
  { label: "Medicine and Surgery", value: "medicine_and_surgery" },
  { label: "Microbiology", value: "microbiology" },
  { label: "Nursing", value: "nursing" },
  { label: "Pharmacy", value: "pharmacy" },
  { label: "Physics", value: "physics" },
  { label: "Political Science", value: "political_science" },
  { label: "Psychology", value: "psychology" },
  { label: "Sociology", value: "sociology" },
  { label: "Statistics", value: "statistics" },
  { label: "Other", value: "other" },
];

// List of common Nigerian universities
export const nigerianUniversities = [
  { label: "University of Lagos", value: "unilag" },
  { label: "University of Ibadan", value: "ui" },
  { label: "Obafemi Awolowo University", value: "oau" },
  { label: "University of Nigeria, Nsukka", value: "unn" },
  { label: "Ahmadu Bello University", value: "abu" },
  { label: "University of Benin", value: "uniben" },
  { label: "University of Ilorin", value: "unilorin" },
  { label: "University of Port Harcourt", value: "uniport" },
  { label: "Federal University of Technology, Akure", value: "futa" },
  { label: "Federal University of Technology, Minna", value: "futminna" },
  { label: "Federal University of Technology, Owerri", value: "futo" },
  { label: "Covenant University", value: "cu" },
  { label: "Landmark University", value: "lmu" },
  { label: "Babcock University", value: "babcock" },
  { label: "Pan-Atlantic University", value: "pau" },
  { label: "American University of Nigeria", value: "aun" },
  { label: "Lagos State University", value: "lasu" },
  { label: "Nnamdi Azikiwe University", value: "unizik" },
  { label: "University of Jos", value: "unijos" },
  { label: "University of Calabar", value: "unical" },
  { label: "Other", value: "other" },
];
